### ISSUE TITLE
Estimate cross-sectional model of playlist choice (as in Aguiar & Waldfogel 2018 JoPE)

### ISSUE THREAD

**Issue by mpachali** [hannesdatta/platformpower#146]
- Much more straightforward to find good instruments, because candidates do not need to be time-varying any longer
- Do listeners of playlists really vary so much on the daily basis?
- Alternatively: Aggregate to the monthly level

**Comment by hannesdatta** [comment]
we have this now.

**Comment by hannesdatta** [comment]
oh no, not a panel model. but, anyways. not relevant.
