### ISSUE TITLE
Quality metric

### ISSUE THREAD

**Issue by mpachali** [hannesdatta/platformpower#152]
- What is song quality? Measuring how many users added this song to the list
- Weighted adding metric by followers as a robustness analysis
- Remove number of tracks added to other playlist by label (e.g., Warner) and add average popularity of remaining content
- If all labels leave, only Indi-content can be added

**Comment by hannesdatta** [comment]
done. 
>Remove number of tracks added to other playlist by label (e.g., Warner) and add average popularity of remaining content
