### ISSUE TITLE
ML techniques for predicting missing listener data

### ISSUE THREAD

**Issue by mpachali** [hannesdatta/platformpower#184]
- @hannesdatta: I think we should invest in predicting the missing listeners based on observed followers for the top 30k playlists covering about 88% of total followers. This is also useful to check how good our current imputation works. I will finish writing the paper based on the current approach, but would like to see the alternative before submitting
- My idea/model:
(1) listeners_pt = f(followers_pt)+e_pt, where f() should be some flexible function trained using ML-techniques
- Data: Use 50k playlists for which we observe followers and listeners to train model (1) --> See "how_many_playlists_have_listeners.R"
- Predict based on trained (1) if listeners are missing, but followers are observed
- **Crucial assumption**: Any time-varying factors (like seasonality, etc.) affect listeners and followers in the same way. Not sure it actually holds, i.e. listeners might go down, whereas followers stay the same. 
- Add (1-Ind(delta_followers_pt>0)) to the regression in (1) --> Ensures that listeners may go down if followers don't change

**Comment by hannesdatta** [comment]
see also #301. we have gaps in followers, too. conducted a new robustness check w/o interpolated observations. pretty robust.
